---
-
  become: yes
  hosts: all
  tasks:
    - name: copy latest CodeDeploy Agent file
      template:
        dest: /home/rwadmin/hardning.sh
        mode: 0777
        src: /home/rwadmin/hardning.sh
