---
- name: Transfer and execute a script.
  hosts: all
  become: yes
  tasks:
     - name: Transfer the script
       copy: src=/home/rwadmin/hardning.sh dest=/home/rwadmin/hardning.sh mode=0777
     - name: Execute the script
       #command: sh /home/rwadmin/hardning.sh
       #local_action: command sudo sh /tmp/new_dormant1.sh
