---
- name: Transfer and execute a script.
  hosts: all
  become: yes
  tasks:
    - name: Transfer the script
      fetch: 
        src: /home/rwadmin/hardning.sh 
        dest: /home/rwadmin/hardning.sh 
        remote_src: true  
        mode: 0777
