---
- name: Transfer and execute a script.
  gather_facts: false
  hosts: all
  become: yes
  tasks:
    - name: Transfer the script
      copy: src=/var/lib/awx/projects/_11__bss_ansible_automation/hardning.sh dest=/tmp/hardning.sh mode=0777
